#!/bin/bash
if [ -z "$1" ]
then
  echo "Please add the filename prefix, for example build-otus devops-2023-03-logging"
  exit 1
fi
if [ ! -e "$1.yaml" ]
then
  echo "File $1.yaml is not exists"
  exit 2
fi
rm -f template.md
wget -q https://raw.githubusercontent.com/dzolotov/otus/main/template.md
cat $1.yaml | jinja2 --format=yaml template.md >$1.md
marp --author Dmitrii Zolotov --keywords otus --description "$1" --pdf $1.md -o $1.pdf --allow-local-files
rm $1.md
rm template.md
echo $1.pdf >>.gitignore
open $1.pdf
