#!/bin/bash
if [ -z "$1" ]
then
  A=lecture
else
  A=$1
fi
if [ ! -e "$A.yaml" ]
then
  echo "File $1.yaml is not exists"
  exit 2
fi
rm -f template.md
wget -q https://raw.githubusercontent.com/dzolotov/otus/main/template.md
cat $A.yaml | jinja2 --format=yaml template.md >$A.md
marp ~/marp/marp.config.js --author Dmitrii Zolotov --keywords otus --description "$1" --pdf $A.md -o $A.pdf --allow-local-files
rm $A.md
rm template.md

grep $A\.pdf .gitignore
if [ $? -ne 0 ]
then
  echo $A.pdf >>.gitignore
fi
open $A.pdf
